domain_path: C:\Users\Aidan_Highsmith1\Box\Softcore_SoC\fpro_walkthrough\vanilla0\export\vanilla0\sw\standalone_microblaze_I
app_src_dir: C:\XilinxVitis\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
